FoodFinder.WEB/Models/Comment.cs
using System;

namespace FoodFinder.Web.Model
{
    public class Comment
    {
        public Guid Id { get; set; }
        public string Title { get; set; }
        public string Detail { get; set; }
        public DateTime Created { get; set; } = DateTime.UtcNow;
        public string CreatedBy { get; set; }
        public bool Deleted { get; set; } = false;
        public string Owner { get; set; }

        public int Likes { get; set; } = 0;

    }
}

FoodFinder.WEB/Controllers/CommentController.cs
using System;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using FoodFinder.Web.Authentication;
using FoodFinder.Web.Model;
using Microsoft.AspNetCore.Authorization;

namespace FoodFinder.Web.Controllers
{
	[Route("Comment")]
	public class CommentController : Controller
	{
		private readonly TemplateContext _db;

		public CommentController(TemplateContext db)
		{
			_db = db;
		}

		/// <summary>
		/// List the 10 latest comments
		/// </summary>
		/// <returns>The index. view</returns>
		[Route("")]
		public IActionResult Index()
		{
			var comments = _db.Comments.OrderByDescending(x => x.Created).Take(10).ToArray();

			return View(comments);
		}

		/// <summary>
		/// Show single comment
		/// </summary>
		/// <returns>The comment.</returns>
		/// <param name="id">Identifier.</param>
		[Route("{id}")]
		public IActionResult Comment(Guid id)
		{
			var comment = _db.Comments.FirstOrDefault(x => x.Id == id);
			return View(comment);
		}


		/// <summary>
		/// Show the create comment page
		/// </summary>
		/// <returns>The create.</returns>
		[Authorize]
		[HttpGet, Route("create")]
		public IActionResult Create()
		{
			return View();
		}

		/// <summary>
		/// Create when user post a comment
		/// </summary>
		/// <returns>The create.</returns>
		/// <param name="comment">Comment.</param>
		[HttpPost, Route("create")]
		public IActionResult Create(Comment comment)
		{
			comment.CreatedBy = User.GetNickName();
			comment.Owner = User.GetUserId();
			comment.Created = DateTime.Now;

			_db.Comments.Add(comment);
			_db.SaveChanges();

			return RedirectToAction($"Index", $"comment", comment.Id);
		}
	}
}

FoodFinder.WEB/Controllers/FeaturesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace FoodFinder.Web.Controllers
{
    public class FeaturesController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }
    }
}

FoodFinder.WEB/Views/Shared/_Comment.cshtml
@model FoodFinder.Web.Model.Comment


<article class="blog-post">
    <div class="h3 ">@Model.Title<div class="pull-right"><small>@Model.Created.ToString("D") by @Model.CreatedBy</small></div></div>

	<div class="content">@Model.Detail</div>
	<div>@if (@Model.Likes != 0) 
		{
		 @Model.Likes
		} else {
		    <button>Like</button>
		}
	</div>
</article>

FoodFinder.WEB/Views/Shared/_Layout.cshtml
@using FoodFinder.Web.Authentication
<!DOCTYPE html>
<html>
<head>
        
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-98132816-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-98132816-1');
</script>

<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<script>
  (adsbygoogle = window.adsbygoogle || []).push({
    google_ad_client: "ca-pub-7315714023067306",
    enable_page_level_ads: true
  });
</script>

        
    <meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE-edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
		
    <title>@ViewData["Title"] - FoodFinder</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>

    <!-- For old IEs -->
    <link rel="shortcut icon" href="favicon.ico" />


    <!-- For new browsers - multisize ico  -->
    <link rel="icon" type="image/x-icon" sizes="16x16 32x32" href="favicon.ico">

    <!-- For iPad with high-resolution Retina display running iOS ≥ 7: -->
    <link rel="apple-touch-icon-precomposed" sizes="152x152" href="favicon-152.png">

    <!-- For iPad with high-resolution Retina display running iOS ≤ 6: -->
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="favicon-144.png">

    <!-- For iPhone with high-resolution Retina display running iOS ≥ 7: -->
    <link rel="apple-touch-icon-precomposed" sizes="120x120" href="favicon-120.png">

    <!-- For iPhone with high-resolution Retina display running iOS ≤ 6: -->
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="favicon-114.png">

    <!-- For iPhone 6+ -->
    <link rel="apple-touch-icon-precomposed" sizes="180x180" href="favicon-180.png">

    <!-- For first- and second-generation iPad: -->
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="favicon-72.png">

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <link rel="apple-touch-icon-precomposed" href="favicon-57.png">

    <!-- For Old Chrome -->
    <link rel="icon" href="favicon-32.png" sizes="32x32">

    <!-- For IE10 Metro -->
    <meta name="msapplication-TileColor" content="#FFFFFF">
    <meta name="msapplication-TileImage" content="favicon-144.png">
    <meta name="theme-color" content="#ffffff">

    <!-- Chrome for Android -->
    <link rel="manifest" href="manifest.json">
    <link rel="icon" sizes="192x192" href="favicon-192.png">

    <script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
                (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
                m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

        ga('create', 'UA-98132816-1', 'auto');
        ga('send', 'pageview');

    </script>

</head>
<body>
		
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
					
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand"><img src="/images/friisconsult.svg" height="30px"></a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Features" asp-action="Index">Fetures</a></li>
                    <li><a asp-area="" asp-controller="Venue" asp-action="Index">Venues</a></li>
                    <li><a asp-area="" asp-controller="Comment" asp-action="Index">Let's talk</a></li>

                </ul>
					 @if (User.Identity.IsAuthenticated)
                {
                    <a  asp-controller="Account" asp-action="Logout" class="btn btn-default navbar-btn navbar-right">Logout @User.GetNickName()</a>
                }
                else
                {
                    <a asp-controller="Account" asp-action="Login" class="btn btn-default navbar-btn navbar-right">Login</a>
                }

            </div>
        </div>
    </nav>
    <div class="container">
        @RenderBody()
        <hr />
        <footer class=" text-center">
            <p><span class="glyphicon glyphicon-copyright-mark"></span> 2018 - <a href="https://friisconsult.com">Per Friis Consult ApS</a> & <a href="https://friismobility.com">Friis Mobility ApS</a> </p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>